dreamer_v2:
  wm_type: v2 
  #Training:
  batch_length: 64
  batch_size: 16
  # amp: False  # AMP no longer helps on A100
  probe_gradients: False  # for baselines
  

dreamer_v3:
  wm_type: v3
  # Training_v3
  batch_size: 16
  batch_length: 64
  adam_lr: 1.0e-4
  adam_lr_actor: 3.0e-5
  adam_lr_critic: 3.0e-5
  adam_eps: 1.0e-8
  # train_ratio: 512
  # pretrain: 100
  grad_clip: 1000
  adam_ac_eps: 1.0e-5
  value_grad_clip: 100
  actor_grad_clip: 100
  probe_gradients: False
  # encoder: {mlp_keys: '$^', cnn_keys: 'image'}
  # decoder: {mlp_keys: '$^', cnn_keys: 'image'}
  # dataset_size: 1000000

  # a2c.
  discount: 0.997
  imag_gradient_mix: '0.0'
  # actor_dist: 'normal'
  actor